#!/bin/bash

# Script to create remaining translation files for i18n
LOCALES_DIR="frontend/src/locales"

# Chinese (Simplified) - zh-CN
mkdir -p "$LOCALES_DIR/zh-CN"
cat > "$LOCALES_DIR/zh-CN/waitlist.json" << 'EOF'
{"title":"等候名单","subtitle":"管理等待服务的客户","tabs":{"active":"活跃 ({{count}})","completed":"已完成 ({{count}})"},"status":{"WAITING":"等待中","CALLED":"已叫号","SEATED":"已就座","CANCELLED":"已取消","NO_SHOW":"未到场"},"stats":{"inQueue":"队列中","servedToday":"今日已服务","avgWaitTime":"平均等待时间","lastMinutes":"(最近 {{minutes}} 分钟)","estimated":"估计"},"entry":{"timeInQueue":"排队时间","calledSince":"叫号后","calledFor":"叫号后","eta":"预计: {{time}}","callingAnytime":"随时叫号","calculating":"计算中...","partySize":"人数","customer":"客户","customerCalled":"客户已被叫号","at":"在","delay":"延迟","delaySeating":"就座延迟"},"actions":{"call":"叫号","seat":"就座","cancel":"取消","noShow":"未到场","addToQueue":"添加到队列","addCustomer":"添加客户"},"form":{"title":"添加到队列","customerPhone":"客户电话","customerName":"客户姓名","fullName":"全名","partySize":"人数","notes":"备注","notesPlaceholder":"例如: 靠窗座位, 婴儿椅...","phonePlaceholder":"电话号码","phonePlaceholderBR":"(11) 99999-9999","lookingUp":"查找客户...","customerFound":"找到客户: {{name}}","newCustomer":"新客户 — 将被注册"},"empty":{"title":"队列中没有客户","description":"添加客户到等候名单以开始服务","action":"添加客户"},"loading":"加载队列...","activeQueue":"活跃队列"}
EOF

cat > "$LOCALES_DIR/zh-CN/customers.json" << 'EOF'
{"title":"客户","subtitle":"管理餐厅客户登记","actions":{"newCustomer":"新客户","editCustomer":"编辑客户","deleteCustomer":"删除客户","saveChanges":"保存更改","registerCustomer":"注册客户"},"filters":{"name":"姓名","namePlaceholder":"按姓名搜索...","phone":"电话","phonePlaceholder":"(DDD) 号码","lastVisitAfter":"最后访问之后","clearFilters":"清除筛选"},"table":{"name":"姓名","phone":"电话","email":"电子邮件","lastVisit":"最后访问","totalVisits":"访问次数","actions":"操作","edit":"编辑","remove":"删除"},"form":{"phone":"电话","phonePlaceholder":"电话号码","phonePlaceholderBR":"(DDD) 号码","name":"姓名","email":"电子邮件 (可选)","notes":"备注 (可选)","notesPlaceholder":"例如: VIP客户, 特殊偏好..."},"empty":{"title":"未找到客户","description":"注册第一个客户或调整搜索筛选","action":"注册客户"},"delete":{"title":"确认删除","message":"您确定要删除客户 <strong>{{name}}</strong> 吗?","warning":"此操作无法撤消。访问历史将被保留,但客户将无法再与新条目关联。"},"pagination":{"showing":"显示 {{from}} 到 {{to}},共 {{total}} 个客户","previous":"上一页","next":"下一页"},"loading":"加载客户...","never":"从未"}
EOF

cat > "$LOCALES_DIR/zh-CN/settings.json" << 'EOF'
{"title":"餐厅设置","subtitle":"管理您的操作偏好和警报。","sections":{"queueAlerts":{"title":"队列时间警报","waitingAlert":{"label":"等待客户警报 (分钟)","help":"定义等待多长时间后客户将被标记为视觉警报。","helpExtra":"留空以禁用。","placeholder":"例如: 15"},"calledAlert":{"label":"已叫号客户警报 (分钟)","help":"定义叫号后多长时间(未就座)客户将被标记为警报。","helpExtra":"留空以禁用。","placeholder":"例如: 5"}},"avgWaitCalculation":{"title":"平均等待时间计算","window":{"label":"计算窗口 (分钟)","help":"仅考虑在最近 X 分钟内进入队列的客户来计算平均时间。","placeholder":"90"},"fallback":{"label":"平均时间回退 (分钟)","help":"当配置的窗口中没有足够数据时显示的值。","placeholder":"15"}}},"validation":{"mustBePositive":"值必须大于 0"},"actions":{"save":"保存更改","saving":"保存中..."},"messages":{"saveSuccess":"设置保存成功!"}}
EOF

# Japanese - ja
mkdir -p "$LOCALES_DIR/ja"
cat > "$LOCALES_DIR/ja/waitlist.json" << 'EOF'
{"title":"待機リスト","subtitle":"サービス待ちの顧客を管理","tabs":{"active":"アクティブ ({{count}})","completed":"完了 ({{count}})"},"status":{"WAITING":"待機中","CALLED":"呼び出し済み","SEATED":"着席済み","CANCELLED":"キャンセル","NO_SHOW":"不在"},"stats":{"inQueue":"待機中","servedToday":"本日サービス済み","avgWaitTime":"平均待機時間","lastMinutes":"(最近 {{minutes}} 分)","estimated":"推定"},"entry":{"timeInQueue":"待機時間","calledSince":"呼び出し後","calledFor":"呼び出し後","eta":"推定: {{time}}","callingAnytime":"いつでも呼び出し","calculating":"計算中...","partySize":"人数","customer":"顧客","customerCalled":"顧客が呼び出されました","at":"で","delay":"遅延","delaySeating":"着席遅延"},"actions":{"call":"呼び出し","seat":"着席","cancel":"キャンセル","noShow":"不在","addToQueue":"キューに追加","addCustomer":"顧客を追加"},"form":{"title":"キューに追加","customerPhone":"顧客電話","customerName":"顧客名","fullName":"フルネーム","partySize":"人数","notes":"メモ","notesPlaceholder":"例: 窓際の席, ベビーチェア...","phonePlaceholder":"電話番号","phonePlaceholderBR":"(11) 99999-9999","lookingUp":"顧客を検索中...","customerFound":"顧客が見つかりました: {{name}}","newCustomer":"新規顧客 — 登録されます"},"empty":{"title":"キューに顧客がいません","description":"サービスを開始するために待機リストに顧客を追加してください","action":"顧客を追加"},"loading":"キューを読み込み中...","activeQueue":"アクティブキュー"}
EOF

cat > "$LOCALES_DIR/ja/customers.json" << 'EOF'
{"title":"顧客","subtitle":"レストランの顧客登録を管理","actions":{"newCustomer":"新規顧客","editCustomer":"顧客を編集","deleteCustomer":"顧客を削除","saveChanges":"変更を保存","registerCustomer":"顧客を登録"},"filters":{"name":"名前","namePlaceholder":"名前で検索...","phone":"電話","phonePlaceholder":"(DDD) 番号","lastVisitAfter":"最終訪問後","clearFilters":"フィルターをクリア"},"table":{"name":"名前","phone":"電話","email":"メール","lastVisit":"最終訪問","totalVisits":"訪問回数","actions":"アクション","edit":"編集","remove":"削除"},"form":{"phone":"電話","phonePlaceholder":"電話番号","phonePlaceholderBR":"(DDD) 番号","name":"名前","email":"メール (任意)","notes":"メモ (任意)","notesPlaceholder":"例: VIP顧客, 特別な好み..."},"empty":{"title":"顧客が見つかりません","description":"最初の顧客を登録するか、検索フィルターを調整してください","action":"顧客を登録"},"delete":{"title":"削除の確認","message":"顧客 <strong>{{name}}</strong> を削除してもよろしいですか?","warning":"この操作は元に戻せません。訪問履歴は保持されますが、顧客は新しいエントリに関連付けることができなくなります。"},"pagination":{"showing":"{{total}} 件中 {{from}} から {{to}} を表示","previous":"前へ","next":"次へ"},"loading":"顧客を読み込み中...","never":"なし"}
EOF

cat > "$LOCALES_DIR/ja/settings.json" << 'EOF'
{"title":"レストラン設定","subtitle":"操作の設定とアラートを管理します。","sections":{"queueAlerts":{"title":"キュー時間アラート","waitingAlert":{"label":"待機中の顧客アラート (分)","help":"待機時間が経過すると顧客に視覚的なアラートが表示されます。","helpExtra":"無効にするには空白のままにしてください。","placeholder":"例: 15"},"calledAlert":{"label":"呼び出し済み顧客アラート (分)","help":"呼び出し後(着席していない)の時間が経過すると顧客にアラートが表示されます。","helpExtra":"無効にするには空白のままにしてください。","placeholder":"例: 5"}},"avgWaitCalculation":{"title":"平均待機時間の計算","window":{"label":"計算ウィンドウ (分)","help":"平均時間を計算するために、最近 X 分以内にキューに入った顧客のみを考慮します。","placeholder":"90"},"fallback":{"label":"平均時間のフォールバック (分)","help":"設定されたウィンドウに十分なデータがない場合に表示される値。","placeholder":"15"}}},"validation":{"mustBePositive":"値は 0 より大きくなければなりません"},"actions":{"save":"変更を保存","saving":"保存中..."},"messages":{"saveSuccess":"設定が正常に保存されました!"}}
EOF

echo "Created Chinese and Japanese translation files"

# Russian - ru
mkdir -p "$LOCALES_DIR/ru"
cat > "$LOCALES_DIR/ru/waitlist.json" << 'EOF'
{"title":"Список Ожидания","subtitle":"Управление клиентами, ожидающими обслуживания","tabs":{"active":"Активная ({{count}})","completed":"Завершенная ({{count}})"},"status":{"WAITING":"Ожидание","CALLED":"Вызван","SEATED":"Размещен","CANCELLED":"Отменен","NO_SHOW":"Не Явился"},"stats":{"inQueue":"В Очереди","servedToday":"Обслужено Сегодня","avgWaitTime":"Среднее Время до Вызова","lastMinutes":"(последние {{minutes}} мин)","estimated":"Оценочно"},"entry":{"timeInQueue":"Время в Очереди","calledSince":"Вызван назад","calledFor":"Вызван назад","eta":"Оценка: {{time}}","callingAnytime":"Вызов в любое время","calculating":"Вычисление...","partySize":"Человек","customer":"Клиент","customerCalled":"Клиент был вызван","at":"в","delay":"Задержка","delaySeating":"Задержка Размещения"},"actions":{"call":"Вызвать","seat":"Разместить","cancel":"Отменить","noShow":"Не Явился","addToQueue":"Добавить в Очередь","addCustomer":"Добавить Клиента"},"form":{"title":"Добавить в Очередь","customerPhone":"Телефон Клиента","customerName":"Имя Клиента","fullName":"Полное имя","partySize":"Человек","notes":"Примечания","notesPlaceholder":"Например: Столик у окна, детский стульчик...","phonePlaceholder":"Номер телефона","phonePlaceholderBR":"(11) 99999-9999","lookingUp":"Поиск клиента...","customerFound":"Клиент найден: {{name}}","newCustomer":"Новый клиент — будет зарегистрирован"},"empty":{"title":"Нет клиентов в очереди","description":"Добавьте клиентов в список ожидания, чтобы начать обслуживание","action":"Добавить Клиента"},"loading":"Загрузка очереди...","activeQueue":"Активная Очередь"}
EOF

cat > "$LOCALES_DIR/ru/customers.json" << 'EOF'
{"title":"Клиенты","subtitle":"Управление регистрацией клиентов ресторана","actions":{"newCustomer":"Новый Клиент","editCustomer":"Редактировать Клиента","deleteCustomer":"Удалить Клиента","saveChanges":"Сохранить Изменения","registerCustomer":"Зарегистрировать Клиента"},"filters":{"name":"Имя","namePlaceholder":"Поиск по имени...","phone":"Телефон","phonePlaceholder":"(DDD) Номер","lastVisitAfter":"Последний визит после","clearFilters":"Очистить Фильтры"},"table":{"name":"Имя","phone":"Телефон","email":"Email","lastVisit":"Последний Визит","totalVisits":"Кол-во Визитов","actions":"Действия","edit":"Редактировать","remove":"Удалить"},"form":{"phone":"Телефон","phonePlaceholder":"Номер телефона","phonePlaceholderBR":"(DDD) Номер","name":"Имя","email":"Email (необязательно)","notes":"Примечания (необязательно)","notesPlaceholder":"Например: VIP клиент, особые предпочтения..."},"empty":{"title":"Клиенты не найдены","description":"Зарегистрируйте первого клиента или настройте фильтры поиска","action":"Зарегистрировать Клиента"},"delete":{"title":"Подтвердить Удаление","message":"Вы уверены, что хотите удалить клиента <strong>{{name}}</strong>?","warning":"Это действие нельзя отменить. История посещений будет сохранена, но клиент больше не сможет быть связан с новыми записями."},"pagination":{"showing":"Показано с {{from}} по {{to}} из {{total}} клиентов","previous":"Предыдущая","next":"Следующая"},"loading":"Загрузка клиентов...","never":"Никогда"}
EOF

cat > "$LOCALES_DIR/ru/settings.json" << 'EOF'
{"title":"Настройки Ресторана","subtitle":"Управление настройками и оповещениями вашей работы.","sections":{"queueAlerts":{"title":"Оповещения Времени Очереди","waitingAlert":{"label":"Оповещение для Ожидающего Клиента (минуты)","help":"Определяет, через сколько времени ожидания клиент будет отмечен визуальным оповещением.","helpExtra":"Оставьте пустым для отключения.","placeholder":"Например: 15"},"calledAlert":{"label":"Оповещение для Вызванного Клиента (минуты)","help":"Определяет, через сколько времени после вызова (без размещения) клиент будет отмечен оповещением.","helpExtra":"Оставьте пустым для отключения.","placeholder":"Например: 5"}},"avgWaitCalculation":{"title":"Расчет Среднего Времени Очереди","window":{"label":"Окно расчета (минуты)","help":"Учитывать только клиентов, вошедших в очередь за последние X минут для расчета среднего времени.","placeholder":"90"},"fallback":{"label":"Резервное среднее время (минуты)","help":"Значение, отображаемое при недостатке данных в настроенном окне.","placeholder":"15"}}},"validation":{"mustBePositive":"Значение должно быть больше 0"},"actions":{"save":"Сохранить Изменения","saving":"Сохранение..."},"messages":{"saveSuccess":"Настройки успешно сохранены!"}}
EOF

echo "Created Russian translation files"

# Polish - pl
mkdir -p "$LOCALES_DIR/pl"
cat > "$LOCALES_DIR/pl/waitlist.json" << 'EOF'
{"title":"Lista Oczekujących","subtitle":"Zarządzaj klientami oczekującymi na obsługę","tabs":{"active":"Aktywna ({{count}})","completed":"Zakończona ({{count}})"},"status":{"WAITING":"Oczekujący","CALLED":"Wezwany","SEATED":"Posadzony","CANCELLED":"Anulowany","NO_SHOW":"Nie Stawił Się"},"stats":{"inQueue":"W Kolejce","servedToday":"Obsłużeni Dziś","avgWaitTime":"Średni Czas do Wezwania","lastMinutes":"(ostatnie {{minutes}} min)","estimated":"Szacowany"},"entry":{"timeInQueue":"Czas w Kolejce","calledSince":"Wezwany od","calledFor":"Wezwany od","eta":"Szacunek: {{time}}","callingAnytime":"Wezwanie w dowolnym momencie","calculating":"Obliczanie...","partySize":"Osoby","customer":"Klient","customerCalled":"Klient został wezwany","at":"o","delay":"Opóźnienie","delaySeating":"Opóźnienie Posadzenia"},"actions":{"call":"Wezwij","seat":"Posadź","cancel":"Anuluj","noShow":"Nie Stawił Się","addToQueue":"Dodaj do Kolejki","addCustomer":"Dodaj Klienta"},"form":{"title":"Dodaj do Kolejki","customerPhone":"Telefon Klienta","customerName":"Imię Klienta","fullName":"Pełne imię","partySize":"Osoby","notes":"Uwagi","notesPlaceholder":"Np: Stolik przy oknie, krzesełko dla dziecka...","phonePlaceholder":"Numer telefonu","phonePlaceholderBR":"(11) 99999-9999","lookingUp":"Wyszukiwanie klienta...","customerFound":"Znaleziono klienta: {{name}}","newCustomer":"Nowy klient — zostanie zarejestrowany"},"empty":{"title":"Brak klientów w kolejce","description":"Dodaj klientów do listy oczekujących, aby rozpocząć obsługę","action":"Dodaj Klienta"},"loading":"Ładowanie kolejki...","activeQueue":"Aktywna Kolejka"}
EOF

cat > "$LOCALES_DIR/pl/customers.json" << 'EOF'
{"title":"Klienci","subtitle":"Zarządzaj rejestracją klientów restauracji","actions":{"newCustomer":"Nowy Klient","editCustomer":"Edytuj Klienta","deleteCustomer":"Usuń Klienta","saveChanges":"Zapisz Zmiany","registerCustomer":"Zarejestruj Klienta"},"filters":{"name":"Nazwa","namePlaceholder":"Szukaj po nazwie...","phone":"Telefon","phonePlaceholder":"(DDD) Numer","lastVisitAfter":"Ostatnia wizyta po","clearFilters":"Wyczyść Filtry"},"table":{"name":"Nazwa","phone":"Telefon","email":"Email","lastVisit":"Ostatnia Wizyta","totalVisits":"Liczba Wizyt","actions":"Akcje","edit":"Edytuj","remove":"Usuń"},"form":{"phone":"Telefon","phonePlaceholder":"Numer telefonu","phonePlaceholderBR":"(DDD) Numer","name":"Nazwa","email":"Email (opcjonalnie)","notes":"Uwagi (opcjonalnie)","notesPlaceholder":"Np: Klient VIP, specjalne preferencje..."},"empty":{"title":"Nie znaleziono klientów","description":"Zarejestruj pierwszego klienta lub dostosuj filtry wyszukiwania","action":"Zarejestruj Klienta"},"delete":{"title":"Potwierdź Usunięcie","message":"Czy na pewno chcesz usunąć klienta <strong>{{name}}</strong>?","warning":"Tej akcji nie można cofnąć. Historia wizyt zostanie zachowana, ale klient nie będzie mógł być powiązany z nowymi wpisami."},"pagination":{"showing":"Wyświetlanie od {{from}} do {{to}} z {{total}} klientów","previous":"Poprzednia","next":"Następna"},"loading":"Ładowanie klientów...","never":"Nigdy"}
EOF

cat > "$LOCALES_DIR/pl/settings.json" << 'EOF'
{"title":"Ustawienia Restauracji","subtitle":"Zarządzaj preferencjami i alertami swojej działalności.","sections":{"queueAlerts":{"title":"Alerty Czasu Kolejki","waitingAlert":{"label":"Alert dla Oczekującego Klienta (minuty)","help":"Określa, po jakim czasie oczekiwania klient zostanie oznaczony wizualnym alertem.","helpExtra":"Pozostaw puste, aby wyłączyć.","placeholder":"Np: 15"},"calledAlert":{"label":"Alert dla Wezwanego Klienta (minuty)","help":"Określa, po jakim czasie od wezwania (bez posadzenia) klient zostanie oznaczony alertem.","helpExtra":"Pozostaw puste, aby wyłączyć.","placeholder":"Np: 5"}},"avgWaitCalculation":{"title":"Obliczanie Średniego Czasu Kolejki","window":{"label":"Okno obliczeniowe (minuty)","help":"Uwzględniaj tylko klientów, którzy dołączyli do kolejki w ciągu ostatnich X minut do obliczenia średniego czasu.","placeholder":"90"},"fallback":{"label":"Rezerwowy średni czas (minuty)","help":"Wartość wyświetlana, gdy w skonfigurowanym oknie nie ma wystarczających danych.","placeholder":"15"}}},"validation":{"mustBePositive":"Wartość musi być większa niż 0"},"actions":{"save":"Zapisz Zmiany","saving":"Zapisywanie..."},"messages":{"saveSuccess":"Ustawienia zapisane pomyślnie!"}}
EOF

echo "Created Polish translation files"

# Arabic - ar
mkdir -p "$LOCALES_DIR/ar"
cat > "$LOCALES_DIR/ar/waitlist.json" << 'EOF'
{"title":"قائمة الانتظار","subtitle":"إدارة العملاء في انتظار الخدمة","tabs":{"active":"نشط ({{count}})","completed":"مكتمل ({{count}})"},"status":{"WAITING":"في الانتظار","CALLED":"تم الاتصال","SEATED":"جالس","CANCELLED":"ملغى","NO_SHOW":"لم يحضر"},"stats":{"inQueue":"في الطابور","servedToday":"تم خدمتهم اليوم","avgWaitTime":"متوسط الوقت حتى الاتصال","lastMinutes":"(آخر {{minutes}} دقيقة)","estimated":"تقديري"},"entry":{"timeInQueue":"الوقت في الطابور","calledSince":"تم الاتصال منذ","calledFor":"تم الاتصال منذ","eta":"التقدير: {{time}}","callingAnytime":"الاتصال في أي وقت","calculating":"جاري الحساب...","partySize":"الأشخاص","customer":"العميل","customerCalled":"تم الاتصال بالعميل","at":"في","delay":"تأخير","delaySeating":"تأخير الجلوس"},"actions":{"call":"اتصل","seat":"أجلس","cancel":"إلغاء","noShow":"لم يحضر","addToQueue":"إضافة إلى الطابور","addCustomer":"إضافة عميل"},"form":{"title":"إضافة إلى الطابور","customerPhone":"هاتف العميل","customerName":"اسم العميل","fullName":"الاسم الكامل","partySize":"الأشخاص","notes":"ملاحظات","notesPlaceholder":"مثال: طاولة بجانب النافذة، كرسي أطفال...","phonePlaceholder":"رقم الهاتف","phonePlaceholderBR":"(11) 99999-9999","lookingUp":"البحث عن العميل...","customerFound":"تم العثور على العميل: {{name}}","newCustomer":"عميل جديد — سيتم تسجيله"},"empty":{"title":"لا يوجد عملاء في الطابور","description":"أضف عملاء إلى قائمة الانتظار لبدء الخدمة","action":"إضافة عميل"},"loading":"جاري تحميل الطابور...","activeQueue":"الطابور النشط"}
EOF

cat > "$LOCALES_DIR/ar/customers.json" << 'EOF'
{"title":"العملاء","subtitle":"إدارة تسجيل عملاء المطعم","actions":{"newCustomer":"عميل جديد","editCustomer":"تعديل العميل","deleteCustomer":"حذف العميل","saveChanges":"حفظ التغييرات","registerCustomer":"تسجيل العميل"},"filters":{"name":"الاسم","namePlaceholder":"البحث بالاسم...","phone":"الهاتف","phonePlaceholder":"(DDD) الرقم","lastVisitAfter":"آخر زيارة بعد","clearFilters":"مسح الفلاتر"},"table":{"name":"الاسم","phone":"الهاتف","email":"البريد الإلكتروني","lastVisit":"آخر زيارة","totalVisits":"عدد الزيارات","actions":"الإجراءات","edit":"تعديل","remove":"حذف"},"form":{"phone":"الهاتف","phonePlaceholder":"رقم الهاتف","phonePlaceholderBR":"(DDD) الرقم","name":"الاسم","email":"البريد الإلكتروني (اختياري)","notes":"ملاحظات (اختياري)","notesPlaceholder":"مثال: عميل VIP، تفضيلات خاصة..."},"empty":{"title":"لم يتم العثور على عملاء","description":"سجل العميل الأول أو اضبط فلاتر البحث","action":"تسجيل العميل"},"delete":{"title":"تأكيد الحذف","message":"هل أنت متأكد من رغبتك في حذف العميل <strong>{{name}}</strong>؟","warning":"لا يمكن التراجع عن هذا الإجراء. سيتم الاحتفاظ بسجل الزيارات، ولكن لن يتمكن العميل من الارتباط بإدخالات جديدة."},"pagination":{"showing":"عرض {{from}} إلى {{to}} من {{total}} عميل","previous":"السابق","next":"التالي"},"loading":"جاري تحميل العملاء...","never":"أبداً"}
EOF

cat > "$LOCALES_DIR/ar/settings.json" << 'EOF'
{"title":"إعدادات المطعم","subtitle":"إدارة تفضيلات وتنبيهات عملك.","sections":{"queueAlerts":{"title":"تنبيهات وقت الطابور","waitingAlert":{"label":"تنبيه للعميل المنتظر (دقائق)","help":"يحدد بعد كم من الوقت سيتم وضع علامة على العميل بتنبيه بصري.","helpExtra":"اترك فارغاً للتعطيل.","placeholder":"مثال: 15"},"calledAlert":{"label":"تنبيه للعميل المتصل به (دقائق)","help":"يحدد بعد كم من الوقت من الاتصال (دون الجلوس) سيتم وضع علامة على العميل بتنبيه.","helpExtra":"اترك فارغاً للتعطيل.","placeholder":"مثال: 5"}},"avgWaitCalculation":{"title":"حساب متوسط وقت الطابور","window":{"label":"نافذة الحساب (دقائق)","help":"النظر فقط في العملاء الذين دخلوا الطابور في آخر X دقيقة لحساب متوسط الوقت.","placeholder":"90"},"fallback":{"label":"احتياطي متوسط الوقت (دقائق)","help":"القيمة المعروضة عندما لا توجد بيانات كافية في النافذة المكونة.","placeholder":"15"}}},"validation":{"mustBePositive":"يجب أن تكون القيمة أكبر من 0"},"actions":{"save":"حفظ التغييرات","saving":"جاري الحفظ..."},"messages":{"saveSuccess":"تم حفظ الإعدادات بنجاح!"}}
EOF

echo "Created Arabic translation files"
echo "All translation files created successfully!"
