/**
 * Icon Catalog
 * 
 * This is the ONLY file allowed to import from lucide-react.
 * All icon usage in the app must go through the Icon wrapper component.
 */

import {
    // Navigation
    Home,
    LayoutDashboard,
    Users,
    Settings,
    FileText,
    BarChart3,
    CreditCard,

    // Actions
    Plus,
    Edit,
    Trash2,
    Copy,
    Download,
    Upload,
    Search,
    Filter,
    MoreVertical,
    MoreHorizontal,

    // States
    CheckCircle,
    AlertTriangle,
    XCircle,
    Info,
    Loader2,

    // Queue / TakeSeat domain
    Bell,
    Phone,
    MessageSquare,
    Clock,
    Receipt,
    UtensilsCrossed,

    // Additional common icons
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    X,
    Check,
    Eye,
    EyeOff,
    Calendar,
    User,
    Mail,
    Lock,
    LogOut,
    Menu,
    ArrowLeft,
    ArrowRight,
    ExternalLink,
    RefreshCw,
    Save,
    Send,
    Share2,
    Star,
    Heart,
    Bookmark,
    Flag,
    Tag,
    Paperclip,
    Image,
    Video,
    Mic,
    Camera,
    MapPin,
    Globe,
    Wifi,
    WifiOff,
    Smartphone,
    Tablet,
    Monitor,
    Printer,
    HardDrive,
    Cloud,
    CloudOff,
    ShoppingBag,
    ShoppingCart,
    Package,
    Truck,
    DollarSign,
    TrendingUp,
    TrendingDown,
    PieChart,
    Activity,
    Zap,
    Shield,
    AlertCircle,
    HelpCircle,
    Slash,
    Percent,
    Hash,
    AtSign,
    Maximize2,
    Minimize2,
    ZoomIn,
    ZoomOut,
    RotateCw,
    RotateCcw,
    Volume2,
    VolumeX,
    Play,
    Pause,
    SkipBack,
    SkipForward,
    FastForward,
    Rewind,
    Repeat,
    Shuffle,
    List,
    Grid,
    Columns,
    Layers,
    Move,
    Crosshair,
    Target,
    Compass,
    Navigation,
    Anchor,
    Award,
    Gift,
    Briefcase,
    Folder,
    FolderOpen,
    File,
    FilePlus,
    FileEdit,
    FileX,
    Inbox,
    Archive,
    Link,
    Link2,
    Unlink,
    Code,
    Terminal,
    Command,
    Database,
    Server,
    Cpu,
    HardDriveDownload,
    HardDriveUpload,
} from 'lucide-react';

/**
 * Canonical icon catalog
 * Maps semantic names to Lucide icon components
 */
export const ICONS = {
    // Navigation
    home: Home,
    dashboard: LayoutDashboard,
    users: Users,
    settings: Settings,
    documents: FileText,
    reports: BarChart3,
    billing: CreditCard,

    // Actions
    add: Plus,
    edit: Edit,
    delete: Trash2,
    copy: Copy,
    download: Download,
    upload: Upload,
    search: Search,
    filter: Filter,
    more: MoreVertical,
    moreHorizontal: MoreHorizontal,

    // States
    success: CheckCircle,
    warning: AlertTriangle,
    error: XCircle,
    info: Info,
    loading: Loader2,

    // Queue / TakeSeat domain
    notify: Bell,
    call: Phone,
    message: MessageSquare,
    waitTime: Clock,
    receipt: Receipt,
    tableService: UtensilsCrossed,

    // Additional common icons
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    close: X,
    check: Check,
    eye: Eye,
    eyeOff: EyeOff,
    calendar: Calendar,
    user: User,
    mail: Mail,
    lock: Lock,
    logout: LogOut,
    menu: Menu,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    externalLink: ExternalLink,
    refresh: RefreshCw,
    save: Save,
    send: Send,
    share: Share2,
    star: Star,
    heart: Heart,
    bookmark: Bookmark,
    flag: Flag,
    tag: Tag,
    paperclip: Paperclip,
    image: Image,
    video: Video,
    mic: Mic,
    camera: Camera,
    mapPin: MapPin,
    globe: Globe,
    wifi: Wifi,
    wifiOff: WifiOff,
    smartphone: Smartphone,
    tablet: Tablet,
    monitor: Monitor,
    printer: Printer,
    hardDrive: HardDrive,
    cloud: Cloud,
    cloudOff: CloudOff,
    shoppingBag: ShoppingBag,
    shoppingCart: ShoppingCart,
    package: Package,
    truck: Truck,
    dollarSign: DollarSign,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    pieChart: PieChart,
    activity: Activity,
    zap: Zap,
    shield: Shield,
    alertCircle: AlertCircle,
    helpCircle: HelpCircle,
    slash: Slash,
    percent: Percent,
    hash: Hash,
    atSign: AtSign,
    maximize: Maximize2,
    minimize: Minimize2,
    zoomIn: ZoomIn,
    zoomOut: ZoomOut,
    rotateCw: RotateCw,
    rotateCcw: RotateCcw,
    volume: Volume2,
    volumeOff: VolumeX,
    play: Play,
    pause: Pause,
    skipBack: SkipBack,
    skipForward: SkipForward,
    fastForward: FastForward,
    rewind: Rewind,
    repeat: Repeat,
    shuffle: Shuffle,
    list: List,
    grid: Grid,
    columns: Columns,
    layers: Layers,
    move: Move,
    crosshair: Crosshair,
    target: Target,
    compass: Compass,
    navigation: Navigation,
    anchor: Anchor,
    award: Award,
    gift: Gift,
    briefcase: Briefcase,
    folder: Folder,
    folderOpen: FolderOpen,
    file: File,
    filePlus: FilePlus,
    fileEdit: FileEdit,
    fileX: FileX,
    inbox: Inbox,
    archive: Archive,
    link: Link,
    link2: Link2,
    unlink: Unlink,
    code: Code,
    terminal: Terminal,
    command: Command,
    database: Database,
    server: Server,
    cpu: Cpu,
    hardDriveDownload: HardDriveDownload,
    hardDriveUpload: HardDriveUpload,
} as const;

/**
 * Type-safe icon name
 */
export type IconName = keyof typeof ICONS;
