/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary-fixed": "#131b2e",
        "outline": "#767586",
        "surface-dim": "#cbdbf5",
        "secondary-fixed-dim": "#bec6e0",
        "on-surface": "#0b1c30",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "on-secondary-container": "#5c647a",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary": "#565e74",
        "tertiary-container": "#b55d00",
        "secondary-container": "#dae2fd",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "error": "#ba1a1a",
        "tertiary": "#904900",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#703700",
        "on-tertiary-container": "#fffbff",
        "primary-container": "#6063ee",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#494bd6",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dae2fd",
        "outline-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary": "#4648d4",
        "tertiary-fixed": "#ffdcc5",
        "on-surface-variant": "#464554",
        "surface-container": "#e5eeff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "xxl": "64px",
        "sm": "8px",
        "gutter": "24px",
        "max-width": "1280px",
        "margin-desktop": "48px",
        "unit": "4px",
        "xl": "40px"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      boxShadow: {
        'level-2': '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        'level-3': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      }
    }
  },
  plugins: [],
}
